version: '3.7'

services:
  app:
    build:
      context: .
    image: "todo-app:latest"
    container_name: "todo-app"
    ports:
      - "8080:8080"
    volumes:
      - ./config.example.json:/data/config.json
    environment:
      - TODO_CONFIG=/data/config.json
      - TODO_ASSETS=/app/assets
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./dev/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - DB_NAME=todo
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassword
    restart: always
    container_name: "todo-postgres"